export const SITE_URL = "https://ahmedsalman.pages.dev";

export const seoProfile = {
  name: "Ahmed Salman",
  localizedNames: ["أحمد سلمان", "احمد سلمان", "احمد سالمان"],
  primaryHandle: "ahmedsalman74",
  alternateHandles: ["ahmedsalman72", "Ahmed Salman 74", "ahmedsalman74_", "kingsalman74", "salman74_"],
  title: "Ahmed Salman | Senior Backend Software Engineer, Gamer & Streamer",
  role: "Senior Backend Software Engineer",
  description:
    "Ahmed Salman, also known as ahmedsalman74, ahmedsalman72, and أحمد سلمان, is a senior backend software engineer, passionate gamer, and game streamer on Twitch, Kick, TikTok, YouTube, and X/Twitter.",
  shortDescription:
    "Senior backend software engineer, passionate gamer, and game streamer exploring Twitch, Kick, TikTok, X/Twitter, new games, and new technologies.",
  linksTitle:
    "Ahmed Salman Links | Backend Software Engineer, Twitch, Kick, TikTok, X",
  linksDescription:
    "Official Ahmed Salman links profile for ahmedsalman74: senior backend software engineer, gamer, and game streamer across Twitch, Kick, TikTok, YouTube, Instagram, Discord, Spotify, and X/Twitter.",
  searchAliases: [
    "Ahmed Salman",
    "أحمد سلمان",
    "احمد سلمان",
    "احمد سالمان",
    "Ahmed Salman 74",
    "ahmedsalman74",
    "ahmedsalman72",
    "Salman software engineer",
    "Ahmed Salman software engineer",
    "Salman backend developer",
    "Salman Twitch",
    "Salman Kick",
    "Salman TikTok",
    "Salman Twitter",
    "Salman X",
    "Ahmed Salman Twitch",
    "Ahmed Salman Kick",
    "Ahmed Salman TikTok",
    "Ahmed Salman Twitter",
    "ahmedsalman74 Twitch",
    "ahmedsalman74 Kick",
    "ahmedsalman74 TikTok",
    "ahmedsalman74 Twitter",
  ],
  keywords: [
    "Ahmed Salman",
    "أحمد سلمان",
    "احمد سلمان",
    "احمد سالمان",
    "Ahmed Salman 74",
    "ahmedsalman74",
    "ahmedsalman72",
    "ahmedsalman74_",
    "kingsalman74",
    "salman74_",
    "senior backend software engineer",
    "senior backend developer",
    "backend software engineer",
    "Salman software engineer",
    "Ahmed Salman software engineer",
    "Salman backend developer",
    "Node.js developer",
    "TypeScript developer",
    "microservices engineer",
    "cloud backend developer",
    "passionate gamer",
    "game streamer",
    "Twitch streamer",
    "Kick streamer",
    "TikTok creator",
    "Twitter profile",
    "X profile",
    "Salman Twitch",
    "Salman Kick",
    "Salman TikTok",
    "Salman Twitter",
    "ahmedsalman74 Twitch",
    "ahmedsalman74 Kick",
    "ahmedsalman74 TikTok",
    "new games",
    "new technologies",
  ],
  knowsAbout: [
    "Backend Engineering",
    "Node.js",
    "TypeScript",
    "Nest.js",
    "Microservices",
    "Distributed Systems",
    "Cloud Architecture",
    "Game Streaming",
    "Twitch Streaming",
    "Kick Streaming",
    "TikTok Content",
    "X / Twitter",
    "Gaming",
    "New Technologies",
  ],
};

export const allProfileAliases = [
  seoProfile.name,
  ...seoProfile.localizedNames,
  seoProfile.primaryHandle,
  ...seoProfile.alternateHandles,
];

export function absoluteUrl(path = "/") {
  return new URL(path, SITE_URL).toString();
}
